### ISSUE TITLE
Is NFS supported?

### ISSUE THREAD

**Issue by superduper** [sol/reserve#6]
Hi, @sol 

Does reserve work with NFS? 
My setup contains a docker container and a reserve running inside it. Code is located on a shared volume that is mounted inside docker. 

Will it react on source modifications inside src/, or only src/Main.hs? 

Thanks.

**Comment by sol** [comment]
Currently reserve does something equivalent to a :reload in GHCi before serving each request. For that reason you should always end up with the latest version of your code. I imagine NFS should work, as long as your changes are visible inside the container before you do the request.

Cheers.

**Comment by superduper** [comment]
@sol, 
I made an experiment with my setup and it worked! :) Now I can edit code in OS X and have it auto-recompiled inside production environment. This is awesome. Thanks for making reserve.

**Comment by sol** [comment]
You are welcome.  Remember that this is experimental (in particular, it may not work that well if you have many concurrent requests).
